version: '3'
services:
  test:
    build: ./ci_cd
    image: kboiiz/air-quality-test:latest
    volumes:
      - ./:/home/github
    command: tail -f /dev/null

  postgres:
    build: 
      context: ./services/postgres
      dockerfile: Dockerfile.dev

volumes:
  postgres-db-volume: