version: '3'
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: alex@ak0.io
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80