version: '3.8'

services:
  api:
    container_name: air_api
    profiles: ["api", "dev"]
    build: ./services/api
    command: uvicorn main:app --host 0.0.0.0 --port 8100 --reload
    ports:
      - 8100:8100
    volumes:
      - ./services/api:/api
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

  app:
    container_name: air_app
    profiles: ["air_app", "dev"]
    build: ./services/air_app
    command: python wsgi.py
    ports:
      - 8000:5000
    volumes:
      - ./services/air_app:/air_app
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

  
  db:
    image: postgres:14.5-alpine
    profiles: ["api", "air_app", "dev"]
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
