version: '3'
services:
  test:
    container_name: test
    image: kboiiz/air-quality-test:latest
    volumes:
      - ./:/home/github/air-quality
    command: tail -f /dev/null

  postgres:
    build: 
      context: ./services/postgres
      dockerfile: Dockerfile.dev

volumes:
  postgres-db-volume: