name: lint
run-name: ${{ github.actor }} is running linting
on:
  push:
    branches:
      - main
      - develop
      - feature/integration-tests

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - id: id_grab
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT
      - run: echo $GITHUB_OUTPUT
    outputs:
      uid_gid: ${{ steps.id_grab.outputs.uid_gid }}

  lint:
    runs-on: ubuntu-latest
    needs: [configure]
    container:
      image: kboiiz/air-quality:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
    defaults:
      run:
        working-directory: ./
    steps:
      - run: echo {{ needs.configure.outputs.uid_gid }}
      - uses: actions/checkout@v3
      - run: pip install --upgrade pip
      - run: pip install -r ci_cd/lint/requirements.txt
      - run: python -m flake8 .
      - run: python -m black . --check
      - run: python -m bandit -r .
