name: lint
run-name: ${{ github.actor }} is running linting
on:
  push:
    branches:
      - main
      - develop
      - feature/ci-cd

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: [configure]
    container:
      image: kboiiz/air-quality:latest
      options: --user 1001:123
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python -m flake8 .
      - run: python -m black . --check
      - run: python -m bandit -r .
