name: push-deploy-airflow 
run-name: ${{ github.actor }} is running deploy
on:
  push:
    branches:
      - main
      - feature/aws-deploy

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: push with rsync
        run: rsync -av --delete ./ deploy-admin@213.255.227.248:~/air-quality
      - name: push with rsync
        run: rsync -av --delete .env deploy-admin@213.255.227.248:~/air-quality
      - name: push with rsync
        run: rsync -av ./services/etl/dags/.env.airflow deploy-admin@213.255.227.248:~/air-quality/services/etl/dags/
      - name: SSH and run it
        run: |
          ssh -t deploy-admin@213.255.227.248 "cd ~/air-quality && docker compose up --build ; bash"
        # testttttttttt