name: tests
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches:
      - main
      - develop
      - feature/ci-cd
    # paths:
    #   - 'services/api/**'
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: [configure]
    container:
      image: kboiiz/air-quality:latest
      options: --user ${{ env.uid_gid }}
    defaults:
      run:
        working-directory: services/api
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: echo $PWD
      - run: echo $PATH
      - run: pip show -f flake8
      - run: python -m flake8 .
      - run: python -m black . --check
      - run: python -m bandit -r .

  # pytest:
  #   runs-on: ubuntu-latest
  #   needs: [configure]
  #   container:
  #     image: myshkins/talk-booking:latest
  #     options: --user ${{ needs.configure.outputs.uid_gid }}
  #   defaults:
  #     run:
  #       working-directory: services/talk_booking
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: poetry install --no-root
  #     - run: poetry run python -m pytest
