name: tests
run-name: ${{ github.actor }} is running tests
on:
  push:
    branches:
      - main
      - develop
      - feature/ci-cd
    paths:
      - 'services/api/**'

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ env.uid_gid }}
    steps:
      - run: echo "uid_gid=$(id -u):$(id -g)"

  pytest:
    runs-on: ubuntu-latest
    needs: [configure]
    container:
      image: myshkins/talk-booking:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
    defaults:
      run:
        working-directory: services/talk_booking
    steps:
      - uses: actions/checkout@v3
      - run: poetry install --no-root
      - run: poetry run python -m pytest
